Models/EquipmentMachineHistory.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace QA1_SYSTEM.Models
{
    public class EquipmentMachineHistory
    {
        [Key]
        public int EqpMacId { get; set; }

        [ForeignKey("EquipmentMachine")]
        public int EQPid { get; set; }
        public EquipmentMachine EquipmentMachine { get; set; }

        [Required]
        [DisplayName("Trouble Encounter")]
        public string? trouble_encounter { get; set; } = "";

        [Required]
        [DisplayName("Date Encounter")]
        public string? trouble_date { get; set; } = "";

        [Required]
        [DisplayName("Remarks")]
        public string? remarks { get; set; } = "";
    }
}

Controllers/EquipmentMachineHistoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QA1_SYSTEM.Data;
using QA1_SYSTEM.Models;

namespace QA1_SYSTEM.Controllers
{
    public class EquipmentMachineHistoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EquipmentMachineHistoryController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<EquipmentMachineHistory> equipmentMachineHistory = _context.EquipmentMachineHistory.ToList();
            return View(equipmentMachineHistory);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            EquipmentMachineHistory equipmentMachineHistory = new EquipmentMachineHistory();
            return View(equipmentMachineHistory);
        }

        [HttpPost]
        public IActionResult Create(EquipmentMachineHistory equipmentMachineHistory)
        {
            _context.Add(equipmentMachineHistory);
            _context.SaveChanges();

            return RedirectToAction("EditHistory", "EquipmentMachine", new { id = equipmentMachineHistory.EQPid });
        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            EquipmentMachineHistory equipmentMachineHistory = _context.EquipmentMachineHistory
                .Where(a => a.EqpMacId == Id).FirstOrDefault();

            return View(equipmentMachineHistory);

        }

        [HttpPost]
        public IActionResult Edit(EquipmentMachineHistory equipmentMachineHistory)
        {
            _context.Attach(equipmentMachineHistory);
            _context.Entry(equipmentMachineHistory).State = EntityState.Modified;

            _context.SaveChanges();
            return RedirectToAction("EditHistory", "EquipmentMachine", new { id = equipmentMachineHistory.EQPid });

        }
    }
}

Views/EquipmentMachineHistory/Create.cshtml
@model QA1_SYSTEM.Models.EquipmentMachineHistory

@{
    ViewData["Title"] = "Create";
}

<h4>Equipment | Machine Records</h4>
<hr />
<div class="card" style="padding:10px;">
    <form asp-action="Create" asp-controller="EquipmentMachineHistory" method="POST">
        <div class="container">
            <div class="row">
                <div class="col-md-12">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <input readonly hidden asp-for="EQPid" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="trouble_encounter" class="control-label"></label>
                        <input asp-for="trouble_encounter" class="form-control" />
                        <span asp-validation-for="trouble_encounter" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="trouble_date" class="control-label"></label>
                        <input type="date" asp-for="trouble_date" class="form-control" />
                        <span asp-validation-for="trouble_date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="remarks" class="control-label"></label>
                        <textarea asp-for="remarks" class="form-control" rows="4" ></textarea>
                        <span asp-validation-for="remarks" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EquipmentMachineHistory/Edit.cshtml
@model QA1_SYSTEM.Models.EquipmentMachineHistory

@{
    ViewData["Title"] = "Edit";
}

<h4>Equipment | Machine Records</h4>
<hr />
<div class="card" style="padding:20px; width:70%;">
    <form asp-action="Edit">
        <div class="container">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" readonly asp-for="EqpMacId" />
                <input type="hidden" readonly asp-for="EQPid" class="form-control" />
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="trouble_encounter" class="control-label"></label>
                        <input asp-for="trouble_encounter" class="form-control" />
                        <span asp-validation-for="trouble_encounter" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="trouble_date" class="control-label"></label>
                        <input asp-for="trouble_date" class="form-control" />
                        <span asp-validation-for="trouble_date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="remarks" class="control-label"></label>
                        <input asp-for="remarks" class="form-control" />
                        <span asp-validation-for="remarks" class="text-danger"></span>
                    </div>
                    

                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>

        <div style="padding-top:30px;">
            <a asp-controller="EquipmentMachine" asp-action="EditHistory" asp-route-id="@Model.EQPid">Back to List</a>
        </div>
      
    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/EquipmentMachineHistory/Index.cshtml
@model IEnumerable<QA1_SYSTEM.Models.EquipmentMachineHistory>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EquipmentMachine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.trouble_encounter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.trouble_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.remarks)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EquipmentMachine.active_user)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.trouble_encounter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.trouble_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.remarks)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EqpMacId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EqpMacId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EqpMacId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>