Models/Consumables.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace QA1_SYSTEM.Models
{
    public class Consumables
    {
        [Key]
        public int ConsumbleId { get; set; }

        [Required]
        [DisplayName("Request Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime? date_reg { get; set; }

        [Required]
        [DisplayName("Category")]
        public string? item_category { get; set; } = "";

        [Required]
        [DisplayName("Part Number")]
        public string? part_number { get; set; } = "";

        [Required]
        [DisplayName("Description/Specs")]
        public string? item_description { get; set; } = "";

        [Required]
        [DisplayName("Maker")]
        public string? maker { get; set; } = "";

        [Required]
        [DisplayName("Supplier")]
        public string? supplier { get; set; } = "";


        [DisplayName("Total quantity")]
        public string? total_qty { get; set; } = "";

        [Required]
        [DisplayName("Consumable stocks")]
        public string? consum_qty { get; set; } = "";

        [Required]
        [DisplayName("Safety stocks")]
        public string? safety_qty { get; set; } = "";

        [Required]
        [DisplayName("Unit")]
        public string? item_unit { get; set; } = "";

        [DisplayName("Unit price")]
        public string? unit_price { get; set; } = "";

        [DisplayName("Total price")]
        public string? total_price { get; set; } = "";

        [Required]
        [DisplayName("Remarks")]
        public string? item_remarks { get; set; } = "";

        [DisplayName("Currency")]
        public string? currency { get; set; } = "";

        [DisplayName("Picture")]
        public string? item_picture { get; set; } = "";

        [NotMapped]
        public IFormFile _pathPic { get; set; }

        //public virtual ICollection<Requestor>? Requestor { get; set; }
        public virtual List<Requestor> Requestor { get; set; } = new List<Requestor>();
    }
}

Controllers/ConsumablesController.cs
using Azure.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QA1_SYSTEM.Data;
using QA1_SYSTEM.Models;

namespace QA1_SYSTEM.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class ConsumablesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ConsumablesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Consumables> consumableViewModel;
            consumableViewModel = _context.Consumables
                .OrderByDescending(x => x.ConsumbleId) // Assuming 'id' is the ID field
                .ToList();

            // Add the counts to ViewData for access in the View
            ViewData["STOCKS"] = consumableViewModel.Count;



            return View(consumableViewModel);
        }

        public IActionResult IndexCritical()
        {
            List<Consumables> consumableViewModel;
            consumableViewModel = _context.Consumables
                .ToList() // Fetch all records from the database
                .Where(y => int.Parse(y.consum_qty) < 5)
                .OrderByDescending(x => x.item_description) // Assuming 'id' is the ID field
                .ToList();

            // Count the occurrences of each status
            var statusCounts = _context.Consumables
                .AsEnumerable() // Execute the query and bring results to memory
                .Where(y => int.TryParse(y.consum_qty, out int qty) && qty < 5) // Filter data in memory
                .GroupBy(x => x.item_description)
                .Select(group => new
                {
                    Status = group.Key,
                    Count = group.Count()
                })
                .ToList();

            // Add the counts to ViewData for access in the View
            ViewData["REQUEST"] = statusCounts.Count;



            return View(consumableViewModel);
        }

        public IActionResult RequestorIndex()
        {
            List<Consumables> consumableViewModel;
            consumableViewModel = _context.Consumables
                .OrderByDescending(x => x.ConsumbleId) // Assuming 'id' is the ID field
                .ToList();
            return View(consumableViewModel);
        }

        public IActionResult CONLoadData1()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            int start = int.Parse(Request.Form["start"].FirstOrDefault());
            int length = int.Parse(Request.Form["length"].FirstOrDefault());

            // Get global search value
            string searchValue = Request.Form["search[value]"].FirstOrDefault();

            // Query the database based on start, length, filters, etc.
            var query = _context.Consumables.Where(x => x.item_category != null);


            // Apply global search filter
            if (!string.IsNullOrEmpty(searchValue))
            {
                query = query.Where(x =>
                    x.item_category.Contains(searchValue) ||
                    x.part_number.Contains(searchValue) ||
                    x.item_description.Contains(searchValue) ||
                    x.maker.Contains(searchValue) ||
                    x.supplier.Contains(searchValue) ||
                    x.total_qty.Contains(searchValue) ||
                    x.consum_qty.Contains(searchValue) ||
                    x.safety_qty.Contains(searchValue) ||
                    
                    x.item_remarks.Contains(searchValue)
                // ...other fields here
                );
            }

            var data = query.Skip(start).Take(length).ToList();
            var totalCount = query.Count();

            return Json(new { draw = draw, recordsFiltered = totalCount, recordsTotal = totalCount, data = data });
        }

        public IActionResult CONLoadData2()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            int start = int.Parse(Request.Form["start"].FirstOrDefault());
            int length = int.Parse(Request.Form["length"].FirstOrDefault());

            // Query the database based on start, length, filters, etc.
            var query = _context.Consumables.Where(x => x.ConsumbleId != null);

            var data = query.Skip(start).Take(length).ToList();
            var totalCount = query.Count();

            return Json(new { draw = draw, recordsFiltered = totalCount, recordsTotal = totalCount, data = data });
        }

        [HttpGet]
        public IActionResult Create()
        {
            Consumables consumables = new Consumables();
            //consumables.Requestor.Add(new Requestor() { ConsumbleId = 1 });

            return View(consumables);
        }

        [HttpPost]
        public IActionResult Create(Consumables consumables, IFormFile _pathPic)
        {
            //PO
            if (_pathPic != null && _pathPic.Length > 0)
            {
                string uniqueFileNameIMG = $"{Guid.NewGuid()}-{"consumables"}-{_pathPic.FileName}";
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "consumables", uniqueFileNameIMG);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    _pathPic.CopyTo(fileStream);
                }

                consumables.item_picture = uniqueFileNameIMG;
            }

            _context.Add(consumables);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditGet(int id)
        {
            var item = _context.Consumables.FirstOrDefault(p => p.ConsumbleId == id);

            if (item == null)
            {
                // Handle when item with the given ID is not found
                return NotFound(); // Return a 404 Not Found response or some error handling
            }
            return PartialView("~/Views/Consumables/Edit.cshtml", item);
        }


        [HttpGet]
        public IActionResult DetailsGet(int id)
        {
            var item = _context.Consumables.FirstOrDefault(p => p.ConsumbleId == id);

            if (item == null)
            {
                // Handle when item with the given ID is not found
                return NotFound(); // Return a 404 Not Found response or some error handling
            }
            return PartialView("~/Views/Consumables/Details.cshtml", item);
        }



      

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Consumables init = _context.Consumables
                .Include(e => e.Requestor)
                .Where(a => a.ConsumbleId == Id).FirstOrDefault();

            return View(init);

        }

        [HttpPost]
        public IActionResult Edit(Consumables consumables, IFormFile _pathPic)
        {
     
            if (_pathPic != null && _pathPic.Length > 0)
            {
                string uniqueFileNameIMG = $"{Guid.NewGuid()}-{"consumables"}-{_pathPic.FileName}";
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "consumables", uniqueFileNameIMG);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    _pathPic.CopyTo(fileStream);
                }

                consumables.item_picture = uniqueFileNameIMG;
            }
            _context.Attach(consumables);
            _context.Entry(consumables).State = EntityState.Modified;
            _context.Entry(consumables).Property(f => f.item_picture).IsModified = _pathPic != null;
            _context.SaveChanges();

            return RedirectToAction("Index");

        }


        [HttpGet]
        public IActionResult EditCritical(int Id)
        {
            Consumables init = _context.Consumables
                .Include(e => e.Requestor)
                .Where(a => a.ConsumbleId == Id).FirstOrDefault();

            return View(init);

        }

        [HttpPost]
        public IActionResult EditCritical(Consumables consumables, IFormFile _pathPic)
        {

            if (_pathPic != null && _pathPic.Length > 0)
            {
                string uniqueFileNameIMG = $"{Guid.NewGuid()}-{"consumables"}-{_pathPic.FileName}";
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "consumables", uniqueFileNameIMG);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    _pathPic.CopyTo(fileStream);
                }

                consumables.item_picture = uniqueFileNameIMG;
            }
            _context.Attach(consumables);
            _context.Entry(consumables).State = EntityState.Modified;
            _context.Entry(consumables).Property(f => f.item_picture).IsModified = _pathPic != null;
            _context.SaveChanges();

            return RedirectToAction("IndexCritical");

        }


        [HttpGet]
        public IActionResult EditRequest(int Id)
        {
            Consumables consumables = _context.Consumables.Include(e => e.Requestor).Where(a => a.ConsumbleId == Id).FirstOrDefault();
            return View(consumables);

        }

        [HttpPost]
        public IActionResult EditRequest(Consumables consumables, IFormFile _pathPic)
        {
            if (_pathPic != null && _pathPic.Length > 0)
            {
                string uniqueFileNameIMG = $"{Guid.NewGuid()}-{"consumables"}-{_pathPic.FileName}";
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "consumables", uniqueFileNameIMG);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {

Controllers/RequestorController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QA1_SYSTEM.Data;
using QA1_SYSTEM.Models;

namespace QA1_SYSTEM.Controllers
{
    
    public class RequestorController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RequestorController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        
        public IActionResult Index()
        {
            List<Requestor> requestors;
            requestors = _context.Requestor.ToList();
            return View(requestors);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            Requestor requestor = new Requestor();

            return View(requestor);
        }


        [HttpPost]
        public IActionResult Create(Requestor requestor, int Id)
        {
            // Fetch the request_qty value from the submitted form or requestor object
            var requestQty = Convert.ToInt32(requestor.request_qty);

            var consumable = _context.Consumables.FirstOrDefault(a => a.ConsumbleId == requestor.ConsumbleId); // Fetch the consumable you want to update

            // Example calculation logic (modify this based on your actual calculation)
            var consumQty = Convert.ToInt32(consumable.consum_qty); // Replace this with your actual calculation
            var totalQty = Convert.ToInt32(consumable.total_qty);
            var safetyQty = Convert.ToInt32(consumable.safety_qty);
            if (consumQty > 0) {
                consumQty = consumQty - requestQty ;
                totalQty = consumQty + safetyQty;


                consumable.consum_qty = consumQty.ToString();
                consumable.total_qty = totalQty.ToString(); ;
                consumable.safety_qty = safetyQty.ToString();
                // Save changes to the database
                _context.SaveChanges();
            } 
            else if (consumQty < 1)
            {
                safetyQty = safetyQty - requestQty;
                totalQty = consumQty + safetyQty;

                consumable.consum_qty = consumQty.ToString();
                consumable.total_qty = totalQty.ToString(); ;
                consumable.safety_qty = safetyQty.ToString();
                // Save changes to the database
                _context.SaveChanges();
            }
            
            // Update Consumables table based on calculations
           
            
            _context.Add(requestor);
            _context.SaveChanges();
            //return RedirectToAction("Index");
            return RedirectToAction("EditRequest", "Consumables", new { id = requestor.ConsumbleId });
        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Requestor requestor = _context.Requestor
                .Where(a => a.RequestId == Id).FirstOrDefault();

            return View(requestor);

        }

        [HttpPost]
        public IActionResult Edit(Requestor requestor)
        {
            _context.Attach(requestor);
            _context.Entry(requestor).State = EntityState.Modified;

            _context.SaveChanges();
            return RedirectToAction("EditRequest", "Consumables", new { id = requestor.ConsumbleId });

        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Requestor requestor = _context.Requestor
                .Where(a => a.RequestId == id).FirstOrDefault();


            return View(requestor);
        }

        [HttpPost]
        public IActionResult Delete(Requestor requestor, int id)
        {
            var requestorToDelete = _context.Requestor.FirstOrDefault(r => r.RequestId == id);
            if (requestorToDelete != null)
            {
                int getId = requestorToDelete.ConsumbleId;
                //_context.Attach(requestor);
                //_context.Entry(requestor).State = EntityState.Deleted;
                //_context.SaveChanges();

                _context.Requestor.Remove(requestorToDelete);
                _context.SaveChanges();

                return RedirectToAction("EditRequest", "Consumables", new { id = getId });
            }
            return View(requestor);
        }
    }
}

Views/Consumables/Delete.cshtml
@model QA1_SYSTEM.Models.Consumables

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consumables</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date_reg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date_reg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.item_category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.item_category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.part_number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.part_number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.item_description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.item_description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.maker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.maker)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.supplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.supplier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.total_qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.total_qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.consum_qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.consum_qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.safety_qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.safety_qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.item_unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.item_unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.unit_price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.unit_price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.total_price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.total_price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.item_remarks)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.item_remarks)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.currency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.item_picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.item_picture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ConsumbleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Consumables/EditRequest.cshtml
@model QA1_SYSTEM.Models.Consumables

@{
    ViewData["Title"] = "EditRequest";
}
@* <link rel="stylesheet" href="~/lib/bootstrap-5.3.2-dist/css/bootstrap.css"> *@
<h4>Item Request</h4>
<hr />

<div class="card" style="padding:10px;">
    <form asp-action="EditRequest" enctype="multipart/form-data">
        <div class="container">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ConsumbleId" />
                <div class="col-md-6" style="padding-top:10px;">
                    
                    <div class="form-group">
                        <label asp-for="part_number" class="control-label"></label>
                        <input readonly asp-for="part_number" class="form-control" />
                        <span asp-validation-for="part_number" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="item_description" class="control-label"></label>
                        <input readonly asp-for="item_description" class="form-control" />
                        <span asp-validation-for="item_description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input readonly hidden type="date" asp-for="date_reg" class="form-control" />
                    </div>
                    <div class="form-group">
                        <select readonly hidden asp-for="item_category" class="form-control">
                            <option value="">Select</option>
                            <option value="Office Supply">Office Supply</option>
                            <option value="Machine Parts[Replacement]">Machine Parts[Replacement]</option>
                            <option value="Machine Parts[Consumables]">Machine Parts[Consumables]</option>
                            <option value="Machine Parts[Request]">Machine Parts[Request]</option>
                            <option value="Stocks">Stocks</option>
                            <option value="Non-Stocks">Non-Stocks</option>
                            <option value="PPE">PPE</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input readonly hidden asp-for="maker" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input readonly hidden asp-for="supplier" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="total_qty" class="control-label"></label>
                        <input readonly id="total_qty" asp-for="total_qty" class="form-control" />
                        <span asp-validation-for="total_qty" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6" style="padding-top:10px;">
                    <div class="form-group">
                        <label asp-for="consum_qty" class="control-label"></label>
                        <input readonly id="consum_qty" asp-for="consum_qty" oninput="calculateTotals()" class="form-control" />
                        <span asp-validation-for="consum_qty" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="safety_qty" class="control-label"></label>
                        <input readonly id="safety_qty" asp-for="safety_qty" oninput="calculateTotals()" class="form-control" />
                        <span asp-validation-for="safety_qty" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="item_unit" class="control-label"></label>
                        <input readonly asp-for="item_unit" class="form-control" />
                        <span asp-validation-for="item_unit" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input hidden id="unit_price" asp-for="unit_price" oninput="calculateTotalValue()" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input hidden readonly id="total_price" asp-for="total_price" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input hidden readonly asp-for="item_remarks" class="form-control" />
                    </div>
                    <div class="form-group">
                        <select readonly hidden asp-for="currency" class="form-control">
                            <option value="">Select</option>
                            <option value="USD">USD</option>
                            <option value="PHP">PHP</option>
                            <option value="JPY">JPY</option>

                        </select>
                        <span asp-validation-for="currency" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input hidden asp-for="item_picture" class="form-control" />
                    </div>
                    

                </div>
                
               
                
            </div>
        </div>
        <hr />
        <div style="padding:10px;">

            <button type="button" class="btn btn-dark float-end" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Add Data
            </button>
        </div>
        
        

    </form>

    <div class="card" style="padding:15px;">
        <h5 class="card-header">Requestor</h5>
        <hr />
        <div class="table-responsive text-nowrap">
            <table id="consumable_table" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th hidden>

                        </th>
                        <th>
                            Request Date
                        </th>
                        <th>
                            Part Number
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Request Quantity
                        </th>
                        <th>
                            Requestor
                        </th>
                        <th>
                            Reason of request
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Requestor)
                    {
                        <tr>
                            <td hidden>
                                @item.ConsumbleId
                            </td>
                            <td>
                                @item.request_ate
                            </td>
                            <td>
                                @item.part_number
                            </td>
                            <td>
                                @item.item_description
                            </td>
                            <td>
                                @item.request_qty
                            </td>
                            <td>
                                @item.requestor_name
                            </td>
                            <td>
                                @item.reason_request
                            </td>
                            <td>
                                <a asp-controller="Requestor" asp-action="Edit" asp-route-id="@item.RequestId">Edit</a> |
                                <a asp-controller="Requestor" asp-action="Delete" asp-route-id="@item.RequestId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div style="padding-top:10px;">
    <a asp-action="RequestorIndex">Back to List</a>
</div>

<!-- Modal from add data-->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Item Request</h1>
                <div class="outer">
                    <div data-bs-dismiss="modal" class="inner">
                        <label class="labelModal">Back</label>
                    </div>
                </div>
                @* <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">Close</button> *@
            </div>
            <div class="modal-body">
                @{

                    Html.RenderPartial("~/Views/Requestor/Create.cshtml", new QA1_SYSTEM.Models.Requestor { ConsumbleId = Model.ConsumbleId, part_number = Model.part_number, item_description = Model.item_description });
                }
            </div>

        </div>
    </div>
</div>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}