Models/Computers.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QA1_SYSTEM.Models
{
    public class Computers
    {
        [Key]
        public int ComputerId { get; set; }

        [DisplayName("Registration Date")]
        public string? date_reg { get; set; } = "";

        [DisplayName("Category")]
        public string? computer_category { get; set; } = "";

        [DisplayName("Processor Name")]
        public string? processor_name { get; set; } = "";

        [DisplayName("Memory Capactiy Installed")]
        public string? ram_capacity { get; set; } = "";

        [DisplayName("HDD Capacity Installed")]
        public string? hdd_capacty { get; set; } = "";

        [DisplayName("OS")]
        public string? os_installed { get; set; } = "";

        [DisplayName("IP-SDP")]
        public string? ip { get; set; } = "";

        [DisplayName("MAC Address")]
        public string? macAddress { get; set; } = "";

        [DisplayName("Active User")]
        public string? active_user { get; set; } = "";

        [DisplayName("Image")]
        public string? path_pic { get; set; } = "";

        [NotMapped]
        public IFormFile _pathPic { get; set; }

        public virtual List<ComputerHistory> ComputerHistory { get; set; } = new List<ComputerHistory>();
        public virtual List<FixedAssetPC> FixedAssetPC { get; set; } = new List<FixedAssetPC>();
    }
}

Controllers/CompHistoryController.cs
using Azure.Core;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QA1_SYSTEM.Data;
using QA1_SYSTEM.Models;

namespace QA1_SYSTEM.Controllers
{
    public class CompHistoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CompHistoryController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<ComputerHistory> computerHistory;
            computerHistory = _context.ComputerHistory.ToList();
            return View(computerHistory);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            ComputerHistory computerHistory = new ComputerHistory();
            return View(computerHistory);
        }

        [HttpPost]
        public IActionResult Create(ComputerHistory computerHistory)
        {
            _context.Add(computerHistory);
            _context.SaveChanges();

            return RedirectToAction("EditHistory", "Computers", new { id = computerHistory.ComputerId });
        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            ComputerHistory computerHistory = _context.ComputerHistory
                .Where(a => a.CompHistoryId == Id).FirstOrDefault();

            return View(computerHistory);

        }

        [HttpPost]
        public IActionResult Edit(ComputerHistory computerHistory)
        {
            _context.Attach(computerHistory);
            _context.Entry(computerHistory).State = EntityState.Modified;

            _context.SaveChanges();
            return RedirectToAction("EditHistory", "Computers", new { id = computerHistory.ComputerId });

        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            ComputerHistory computerHistory = _context.ComputerHistory
                .Where(a => a.CompHistoryId == id).FirstOrDefault();


            return View(computerHistory);
        }

        [HttpPost]
        public IActionResult Delete(ComputerHistory computerHistory, int id)
        {
            var requestorToDelete = _context.ComputerHistory.FirstOrDefault(r => r.CompHistoryId == id);
            if (requestorToDelete != null)
            {
                int getId = requestorToDelete.ComputerId;

                _context.ComputerHistory.Remove(requestorToDelete);
                _context.SaveChanges();

                return RedirectToAction("EditRequest", "ComputerHistory", new { id = getId });
            }
            return View(computerHistory);
        }


        [HttpGet]
        public IActionResult GetHistoryPartialView(int id)
        {
            var historyData = _context.ComputerHistory
               .Where(a => a.CompHistoryId == id).FirstOrDefault();
            return PartialView("~/Views/CompHistory/Edit.cshtml", historyData);

            
        }
    }
}

Controllers/ComputersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QA1_SYSTEM.Data;
using QA1_SYSTEM.Models;

namespace QA1_SYSTEM.Controllers
{
    public class ComputersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ComputersController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Computers> computers;
            computers = _context.Computers.ToList();
            return View(computers);
        }

        public IActionResult IndexHistory()
        {
            List<Computers> computers;
            computers = _context.Computers.ToList();
            return View(computers);
        }

        public IActionResult IndexFixedAsset()
        {
            List<Computers> computers;
            computers = _context.Computers.ToList();
            return View(computers);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            Computers computers = new Computers();
            return View(computers);
        }

        [HttpPost]
        public IActionResult Create(Computers computers, IFormFile _pathPic)
        {

            if (_pathPic != null && _pathPic.Length > 0)
            {
                string uniqueFileNameIMG = $"{Guid.NewGuid()}-{_pathPic.FileName}";
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "computers", uniqueFileNameIMG);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    _pathPic.CopyTo(fileStream);
                }

                computers.path_pic = uniqueFileNameIMG;
            }

            _context.Add(computers);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Computers computers = _context.Computers.Find(Id);

            return View(computers);

        }

        [HttpPost]
        public IActionResult Edit(Computers computers, IFormFile _pathPic)
        {
            if (_pathPic != null && _pathPic.Length > 0)
            {
                string uniqueFileNameIMG = $"{Guid.NewGuid()}-{_pathPic.FileName}";
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "computers", uniqueFileNameIMG);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    _pathPic.CopyTo(fileStream);
                }

                computers.path_pic = uniqueFileNameIMG;
            }

            _context.Attach(computers);
            _context.Entry(computers).State = EntityState.Modified;
            _context.Entry(computers).Property(f => f.path_pic).IsModified = _pathPic != null;

            _context.SaveChanges();
            return RedirectToAction("Index", "Computers", new { id = computers.ComputerId });

        }

        [HttpGet]
        public IActionResult EditGet(int id)
        {
            var item = _context.Computers.FirstOrDefault(p => p.ComputerId == id);

            if (item == null)
            {
                // Handle when item with the given ID is not found
                return NotFound(); // Return a 404 Not Found response or some error handling
            }
            return PartialView("~/Views/Computers/Edit.cshtml", item);
        }


        [HttpGet]
        public IActionResult DetailsGet(int id)
        {
            var item = _context.Computers.FirstOrDefault(p => p.ComputerId == id);

            if (item == null)
            {
                // Handle when item with the given ID is not found
                return NotFound(); // Return a 404 Not Found response or some error handling
            }
            return PartialView("~/Views/Computers/Details.cshtml", item);
        }



        [Authorize]
        [HttpGet]
        public IActionResult EditHistory(int Id)
        {
            Computers computers = _context.Computers.Include(e => e.ComputerHistory).Where(a => a.ComputerId == Id).FirstOrDefault();

            return View(computers);

        }

        //[HttpPost]
        //public IActionResult EditHistory(Computers computers)
        //{
        //    _context.Attach(computers);
        //    _context.Entry(computers).State = EntityState.Modified;

        //    _context.SaveChanges();
        //    return RedirectToAction("EditHistory", "Computers", new { id = computers.ComputerId });

        //}

        [Authorize]
        [HttpGet]
        public IActionResult EditFixedAsset(int Id)
        {
            Computers computers = _context.Computers.Include(e => e.FixedAssetPC).Where(a => a.ComputerId == Id).FirstOrDefault();

            return View(computers);

        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            Computers computers = _context.Computers
                .Where(a => a.ComputerId == Id)
                .FirstOrDefault();

            return View(computers);
        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Computers computers = _context.Computers
                .Include(e => e.ComputerHistory).Include(e => e.FixedAssetPC)
                .Where(a => a.ComputerId == id).FirstOrDefault();

            return View(computers);
        }

        [HttpPost]
        public IActionResult Delete(Computers computers)
        {
            _context.Attach(computers);
            _context.Entry(computers).State = EntityState.Deleted;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Views/Computers/Create.cshtml
@model QA1_SYSTEM.Models.Computers

@{
    ViewData["Title"] = "Create";
}


<form asp-action="Create" enctype="multipart/form-data">
<div class="d-flex justify-content-between" style="padding:5px;">
    <div><h4>Registration</h4></div>
    <div>
        <input type="submit" value="Create" class="btn btn-primary" style="width:100px" />
    </div>
</div>
<hr />
<div class="card" style="padding:10px;">
    
        <div class="container">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="date_reg" class="control-label"></label>
                        <input type="date" asp-for="date_reg" class="form-control" />
                        <span asp-validation-for="date_reg" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="computer_category" class="control-label"></label>
                        <select required asp-for="computer_category" class="form-control">
                            <option value="">Select</option>
                            <option value="Office Computer">Office Computer</option>
                            <option value="Industrial Computer">Industrial Computer</option>
                            <option value="Computer Server">Computer Server</option>
                            <option value="Network Attached Server">Network Attached Server</option>
                        </select>
                        <span asp-validation-for="computer_category" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="processor_name" class="control-label"></label>
                        <input asp-for="processor_name" class="form-control" />
                        <span asp-validation-for="processor_name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">

                    <div class="form-group">
                        <label asp-for="ram_capacity" class="control-label"></label>
                        <input asp-for="ram_capacity" class="form-control" />
                        <span asp-validation-for="ram_capacity" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="hdd_capacty" class="control-label"></label>
                        <input asp-for="hdd_capacty" class="form-control" />
                        <span asp-validation-for="hdd_capacty" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="os_installed" class="control-label"></label>
                        <input asp-for="os_installed" class="form-control" />
                        <span asp-validation-for="os_installed" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="ip" class="control-label"></label>
                        <input asp-for="ip" class="form-control" oninput="formatIPAddress(this)" />
                        <span asp-validation-for="ip" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="macAddress" class="control-label"></label>
                        <input asp-for="macAddress" class="form-control" />
                        <span asp-validation-for="macAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="active_user" class="control-label"></label>
                        <input asp-for="active_user" class="form-control" />
                        <span asp-validation-for="active_user" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label for="_pathPic">Upload Picture</label>
                        <input type="file" id="_pathPic" name="_pathPic" class="form-control-file" accept=".pdf, .jpg, .jpeg, .png, .gif, .bmp" />
                        <input hidden asp-for="path_pic" class="form-control" />
                    </div>

                </div>
                
            </div>
        </div>
        
    
</div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Computers/Delete.cshtml
@model QA1_SYSTEM.Models.Computers

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Computers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date_reg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date_reg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.computer_category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.computer_category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.processor_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.processor_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ram_capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ram_capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hdd_capacty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hdd_capacty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.os_installed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.os_installed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.macAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.macAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.active_user)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.active_user)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.path_pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.path_pic)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ComputerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Computers/Details.cshtml
@model QA1_SYSTEM.Models.Computers

@{
    ViewData["Title"] = "Details";
}

<h4>Computers</h4>

<div class="card" style="padding:20px;">
    
    <div>
        <div class="col">
            <a href="@Url.Content("~/computers/" + Model.path_pic)" target="_blank">
                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAANBJREFUSEvtlWsNwjAURs8UgAPAARLmACygDFAAEpAwHCABFEA+siZN10fapoQE7s9m9zv3vY7G1jXW56OAHtgDy4KsbsAOuLi+dgb6aFEgblzkv4oBnhXixnVScvvhD1CZqkt0BObAJtCvKsAV0CjLNDEzDyQboIi1F+tRfBhFt8CpFmAilrggB0fwDAgUtdCYPpyIfSLqxb0UoLV3I45pmR3K7oFP1HcgvwOgevpGL3S/UqflnamdrmZcdU9dVOOTDUgNRHWTfxsQzL75T/8FgEAoGdn7svAAAAAASUVORK5CYII=" />
                View Picture
            </a>
        </div>

    </div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date_reg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date_reg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.computer_category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.computer_category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.processor_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.processor_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ram_capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ram_capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hdd_capacty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hdd_capacty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.os_installed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.os_installed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.macAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.macAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.active_user)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.active_user)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.path_pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.path_pic)
        </dd>
    </dl>
</div>
@* <div>
    <a asp-action="Edit" asp-route-id="@Model?.ComputerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div> *@

Views/Computers/EditHistory.cshtml
@model QA1_SYSTEM.Models.Computers


@{
    ViewData["Title"] = "EditHistory";
}


<h4>Computer records</h4>
<hr />
<div class="card" style="padding-top:20px;">
        <form asp-action="EditHistory" enctype="multipart/form-data">
            <div class="container">
                <div class="row">
                    <input type="hidden" asp-for="ComputerId" />
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="date_reg" class="control-label"></label>
                            <input readonly type="date" asp-for="date_reg" class="form-control" />
                            <span asp-validation-for="date_reg" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="computer_category" class="control-label"></label>
                            <select  readonly required asp-for="computer_category" class="form-control">
                                <option value="">Select</option>
                                <option value="Office Computer">Office Computer</option>
                                <option value="Industrial Computer">Industrial Computer</option>
                                <option value="Computer Server">Computer Server</option>
                                <option value="Network Attached Server">Network Attached Server</option>
                            </select>
                            <span asp-validation-for="computer_category" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="processor_name" class="control-label"></label>
                            <input readonly asp-for="processor_name" class="form-control" />
                            <span asp-validation-for="processor_name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">

                        <div class="form-group">
                            <label asp-for="ram_capacity" class="control-label"></label>
                            <input readonly asp-for="ram_capacity" class="form-control" />
                            <span asp-validation-for="ram_capacity" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="hdd_capacty" class="control-label"></label>
                            <input readonly asp-for="hdd_capacty" class="form-control" />
                            <span asp-validation-for="hdd_capacty" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="os_installed" class="control-label"></label>
                            <input readonly asp-for="os_installed" class="form-control" />
                            <span asp-validation-for="os_installed" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="ip" class="control-label"></label>
                            <input readonly asp-for="ip" class="form-control" oninput="formatIPAddress(this)" />
                            <span asp-validation-for="ip" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                        <label asp-for="macAddress" class="control-label"></label>
                        <input readonly asp-for="macAddress" class="form-control" />
                        <span asp-validation-for="macAddress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="active_user" class="control-label"></label>
                            <input  readonly asp-for="active_user" class="form-control" />
                            <span asp-validation-for="active_user" class="text-danger"></span>
                        </div>


                    </div>
                </div>
            </div>
        <div style="padding:10px;">
            <button type="button" class="btn btn-dark float-end" data-bs-toggle="modal" data-bs-target="#createModal">
                Add Data
            </button>
        </div>
        </form>
@* table *@
    <div class="card" style="padding:15px; margin: 5px;">
        <h5 class="card-header">History</h5>
        <hr />
        <div class="table-responsive text-nowrap">
            <table id="computers_table" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>A C T I O N</th>
                        <th>
                            FK
                        </th>
                        <th>
                            Trouble
                        </th>
                        <th>
                            Date Encounter
                        </th>
                        <th>
                            Remarks
                        </th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ComputerHistory)
                    {
                        <tr>
                            <td>
                                <a asp-controller="CompHistory" asp-action="Edit" asp-route-id="@item.CompHistoryId" >Edit</a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Computers.ComputerId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.trouble_encounter)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.trouble_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.remarks)
                            </td>
                            
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    
    </div>



<div style="padding-top:10px;">
    <a asp-action="IndexHistory">Back to List</a>
</div>

<!-- Modal from add data-->
<div class="modal fade" id="createModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Computer History</h1>
                <div class="outer">
                    <div data-bs-dismiss="modal" class="inner">
                        <label class="labelModal">Back</label>
                    </div>
                </div>
                @* <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">Close</button> *@
            </div>
            <div class="modal-body">
                @{

                    Html.RenderPartial("~/Views/CompHistory/Create.cshtml", new QA1_SYSTEM.Models.ComputerHistory { ComputerId = Model.ComputerId });
                }
            </div>

        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


}

Views/Computers/IndexFixedAsset.cshtml
@model IEnumerable<QA1_SYSTEM.Models.Computers>

@{
    ViewData["Title"] = "IndexFixedAsset";
}


<h1>COMPUTER FIXED ASSET</h1>


<div class="card" style="padding:20px;">
    <hr />
    <div class="table-responsive text-nowrap">
        <table id="computers_table" class="display" style="width:100%">
            <thead>
                <tr>
                    <th></th>
                    <th>@Html.DisplayNameFor(model => model.date_reg)</th>
                    <th>@Html.DisplayNameFor(model => model.computer_category)</th>
                    <th>@Html.DisplayNameFor(model => model.processor_name)</th>
                    <th>@Html.DisplayNameFor(model => model.ram_capacity)</th>
                    <th>@Html.DisplayNameFor(model => model.hdd_capacty)</th>
                    <th>@Html.DisplayNameFor(model => model.os_installed)</th>
                    <th>@Html.DisplayNameFor(model => model.ip)</th>
                    <th>@Html.DisplayNameFor(model => model.macAddress)</th>
                    <th>@Html.DisplayNameFor(model => model.active_user)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a asp-action="EditFixedAsset" asp-route-id="@item.ComputerId">View Fixed Asset</a>
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.date_reg)</td>
                        <td>@Html.DisplayFor(modelItem => item.computer_category)</td>
                        <td>@Html.DisplayFor(modelItem => item.processor_name)</td>
                        <td>@Html.DisplayFor(modelItem => item.ram_capacity)</td>
                        <td>@Html.DisplayFor(modelItem => item.hdd_capacty)</td>
                        <td>@Html.DisplayFor(modelItem => item.os_installed)</td>
                        <td>@Html.DisplayFor(modelItem => item.ip)</td>
                        <td>@Html.DisplayFor(modelItem => item.macAddress)</td>
                        <td>@Html.DisplayFor(modelItem => item.active_user)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>