Models/FixedAssetEQP.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace QA1_SYSTEM.Models
{
    public class FixedAssetEQP
    {
        [Key]
        public int EQPassetId { get; set; }

        [ForeignKey("EquipmentMachine")]
        public int EQPid { get; set; }
        public EquipmentMachine EquipmentMachine { get; set; }


        [DisplayName("Fixed Asset")]
        public string? fixed_asset_no { get; set; } = "";

        [DisplayName("Fixed Asset date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = false)]
        public string? fixed_asset_date { get; set; } = "";

        [DisplayName("Inventory Found")]
        public string? inventory_found { get; set; } = "";

        [DisplayName("Inventory Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = false)]
        public string? inventory_date { get; set; }

        [DisplayName("Inventory Year")]
        public string? inventory_year { get; set; }

        [DisplayName("Location")]
        public string? item_location { get; set; }

        [DisplayName("Picture")]
        public string? pic_path { get; set; }

        [NotMapped]
        public IFormFile _pathPic { get; set; }
    }
}

Controllers/FixedAssetEQPController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QA1_SYSTEM.Data;
using QA1_SYSTEM.Models;

namespace QA1_SYSTEM.Controllers
{
    public class FixedAssetEQPController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FixedAssetEQPController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<FixedAssetEQP> fixedAssetEQP = _context.FixedAssetEQP.ToList();
            return View(fixedAssetEQP);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            FixedAssetEQP fixedAssetEQP = new FixedAssetEQP();
            return View(fixedAssetEQP);
        }

        [HttpPost]
        public IActionResult Create(FixedAssetEQP fixedAssetEQP)
        {
            _context.Add(fixedAssetEQP);
            _context.SaveChanges();

            return RedirectToAction("EditFixedAsset", "EquipmentMachine", new { id = fixedAssetEQP.EQPid });
        }

        [Authorize(Roles = "Administrator, Moderator")]
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            FixedAssetEQP equipmentMachineHistory = _context.FixedAssetEQP
                .Where(a => a.EQPassetId == Id).FirstOrDefault();

            return View(equipmentMachineHistory);

        }

        [HttpPost]
        public IActionResult Edit(FixedAssetEQP equipmentMachineHistory)
        {
            _context.Attach(equipmentMachineHistory);
            _context.Entry(equipmentMachineHistory).State = EntityState.Modified;

            _context.SaveChanges();
            return RedirectToAction("EditFixedAsset", "EquipmentMachine", new { id = equipmentMachineHistory.EQPid });

        }
    }
}

Views/FixedAssetEQP/Create.cshtml
@model QA1_SYSTEM.Models.FixedAssetEQP

@{
    ViewData["Title"] = "Create";
}

<h4>Fixed Asset</h4>
<hr />
<div class="card" style="padding:10px;">
    <form asp-action="Create" asp-controller="FixedAssetEQP" method="POST">
        <div class="container">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input required hidden asp-for="EQPid" class="form-control"/>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="fixed_asset_no" class="control-label"></label>
                        <input asp-for="fixed_asset_no" class="form-control" />
                        <span asp-validation-for="fixed_asset_no" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="fixed_asset_date" class="control-label"></label>
                        <input type="date" asp-for="fixed_asset_date" class="form-control" />
                        <span asp-validation-for="fixed_asset_date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="inventory_found" class="control-label"></label>
                        <select required asp-for="inventory_found" class="form-control">
                            <option value="">Select</option>
                            <option value="YES">YES</option>
                            <option value="NO">NO</option>
                        </select>
                        <span asp-validation-for="inventory_found" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="inventory_date" class="control-label"></label>
                        <input type="date" asp-for="inventory_date" class="form-control" />
                        <span asp-validation-for="inventory_date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="inventory_year" class="control-label"></label>
                        <input type="number" asp-for="inventory_year" class="form-control" />
                        <span asp-validation-for="inventory_year" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="item_location" class="control-label"></label>
                        <input asp-for="item_location" class="form-control" />
                        <span asp-validation-for="item_location" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="pic_path" class="control-label"></label>
                        <input asp-for="pic_path" class="form-control" />
                        <span asp-validation-for="pic_path" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        </div>
       
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FixedAssetEQP/Edit.cshtml
@model QA1_SYSTEM.Models.FixedAssetEQP

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FixedAssetEQP</h4>
<hr />
<div class="card" style="padding:20px; width:70%;">
    <form asp-action="Edit">
        <div class="container">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input readonly hidden asp-for="EQPid" class="form-control" />
                <input readonly type="hidden" asp-for="EQPassetId" />
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="fixed_asset_no" class="control-label"></label>
                        <input asp-for="fixed_asset_no" class="form-control" />
                        <span asp-validation-for="fixed_asset_no" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="fixed_asset_date" class="control-label"></label>
                        <input asp-for="fixed_asset_date" class="form-control" />
                        <span asp-validation-for="fixed_asset_date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="inventory_found" class="control-label"></label>
                        <input asp-for="inventory_found" class="form-control" />
                        <span asp-validation-for="inventory_found" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="inventory_date" class="control-label"></label>
                        <input asp-for="inventory_date" class="form-control" />
                        <span asp-validation-for="inventory_date" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="inventory_year" class="control-label"></label>
                        <input asp-for="inventory_year" class="form-control" />
                        <span asp-validation-for="inventory_year" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="item_location" class="control-label"></label>
                        <input asp-for="item_location" class="form-control" />
                        <span asp-validation-for="item_location" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="pic_path" class="control-label"></label>
                        <input asp-for="pic_path" class="form-control" />
                        <span asp-validation-for="pic_path" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
        
    </form>
    <div style="padding-top:30px;">
        <a asp-controller="EquipmentMachine" asp-action="EditFixedAsset" asp-route-id="@Model.EQPid">Back to List</a>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FixedAssetEQP/Index.cshtml
@model IEnumerable<QA1_SYSTEM.Models.FixedAssetEQP>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.EquipmentMachine)</th>
            <th>@Html.DisplayNameFor(model => model.fixed_asset_no)</th>
            <th>@Html.DisplayNameFor(model => model.fixed_asset_date)</th>
            <th>@Html.DisplayNameFor(model => model.inventory_found)</th>
            <th>@Html.DisplayNameFor(model => model.inventory_date)</th>
            <th>@Html.DisplayNameFor(model => model.inventory_year)</th>
            <th>@Html.DisplayNameFor(model => model.item_location)</th>
            <th>@Html.DisplayNameFor(model => model.pic_path)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.EquipmentMachine.active_user)</td>
            <td>@Html.DisplayFor(modelItem => item.fixed_asset_no)</td>
            <td>@Html.DisplayFor(modelItem => item.fixed_asset_date)</td>
            <td>@Html.DisplayFor(modelItem => item.inventory_found)</td>
            <td>@Html.DisplayFor(modelItem => item.inventory_date)</td>
            <td>@Html.DisplayFor(modelItem => item.inventory_year)</td>
            <td>@Html.DisplayFor(modelItem => item.item_location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pic_path)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EQPassetId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EQPassetId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EQPassetId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>